--No semicolon at end, just continue writing next row, all MUST be on the same row for each insert
--INSERT INTO TABLE_NAME(TABLE_COLUMN,...) VALUES(TABLE_VALUE,...)

INSERT INTO DINNERTABLE(TABLESIZE) VALUES (8),(6),(4)

INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-23','Varmrätt','Pasta'),('2023-02-22','Varmrätt','Kött'),('2023-02-22','Varmrätt','Vegetarisk')
INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-24','Varmrätt','Pasta'),('2023-02-24','Varmrätt','Kött'),('2023-02-24','Varmrätt','Vegetarisk')
INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-25','Varmrätt','Pasta'),('2023-02-25','Varmrätt','Kött'),('2023-02-25','Varmrätt','Vegetarisk')
INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-26','Varmrätt','Pasta'),('2023-02-26','Varmrätt','Kött'),('2023-02-26','Varmrätt','Vegetarisk')
INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-27','Varmrätt','Pasta'),('2023-02-27','Varmrätt','Kött'),('2023-02-27','Varmrätt','Vegetarisk')

INSERT INTO ITEMS(DESCRIPTION, ITEMCATEGORY, NAME, PRICE) VALUES ('desc', 'F', 'Toast Skagen', 150)
INSERT INTO ITEMS(DESCRIPTION, ITEMCATEGORY, NAME, PRICE) VALUES ('desc', 'F', 'Bröd', 50)
INSERT INTO ITEMS(DESCRIPTION, ITEMCATEGORY, NAME, PRICE) VALUES ('desc', 'V', 'Oxfilé', 250)
INSERT INTO ITEMS(DESCRIPTION, ITEMCATEGORY, NAME, PRICE) VALUES ('desc', 'V', 'Lax', 175)
INSERT INTO ITEMS(DESCRIPTION, ITEMCATEGORY, NAME, PRICE) VALUES ('desc', 'D', 'Creme Brulee', 120)
INSERT INTO ITEMS(DESCRIPTION, ITEMCATEGORY, NAME, PRICE) VALUES ('desc', 'D', 'Glass', 80)