INSERT INTO DINNERTABLE(TABLESIZE) VALUES (8),(6),(4)

INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-22','Varmrätt','Pasta'),('2023-02-22','Varmrätt','Kött'),('2023-02-22','Varmrätt','Vegetarisk')
INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-23','Varmrätt','Pasta')
INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-23','Varmrätt','Pasta')
INSERT INTO TODAYSLUNCH(DATE, DESCRIPTION, NAME) VALUES ('2023-02-24','Varmrätt','Pasta')
INSERT INTO ITEMS(DESCRIPTION, ITEMCATEGORY, NAME, PRICE) VALUES ('desc', 'V', 'Oxfilé', 250)